version: '3.9'

services:
  voltrent-service:
    image: manhtiennn/voltrent:latest
    container_name: voltrent-main-svc
    restart: always

    ports:
      - "8080:8080"

  postgres:
    image: postgres:latest
    container_name: voltrent-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"