version: '3.9'

services:
  voltrent-service:
    image: manhtiennn/voltrent:latest
    container_name: voltrent-main-svc
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
