spring:
  application:
    name: voltrent
  output:
    ansi:
      enabled: always
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  http:
    codecs:
      max-in-memory-size: 10MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  messages:
    encoding: UTF-8

app:
  jwt:
    secret: 089669ad208ee725fe7a17cadb825bcd1f924f73c022bbbc
    access-token-expiration: 6500
    refresh-token-expiration: 10000

cache:
  booking:
    expiration: 600 # in seconds

aws:
  s3:
    bucket-name: ${BUCKET_NAME}
    region: ${AWS_REGION}
  credentials:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}


server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

httpclient:
  read-timeout: 10000
  connect-timeout: 10000
  write-timeout: 10000


logging:
  level:
    web: DEBUG
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss

payment:
  vnpay:
    tmn-code: 9C79VGSE
    secret-key: KCF9NKM1WT1BMXAFQ3GD69OT1K2V2SA2
    init-payment-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    return-url: https://dev.payment.com/order/%s/status
    timeout: 15 # in minutes

  vietqr:
    client-id: b3c1d186-d571-4403-b06b-067c18a5adf2
    api-key: 5c54c1a2-7cab-42e2-aa76-6fc01c82e910
    base-url: https://api.vietqr.io/v2
    api:
      generate-qr: /generate
