
spring:
  application:
    name: voltrent
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:postgresql://ep-still-wind-a1vsdis6-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_cCtLQIy1bEv3
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  messages:
    encoding: UTF-8
app:
  jwt:
    secret: 089669ad208ee725fe7a17cadb825bcd1f924f73c022bbbc
    access-token-expiration: 6500
    refresh-token-expiration: 10000

cache:
  booking:
    expiration: 600 # in seconds

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  level:
    web: DEBUG
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss

payment:
  vnpay:
    tmn-code: 9C79VGSE
    secret-key: KCF9NKM1WT1BMXAFQ3GD69OT1K2V2SA2
    init-payment-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    return-url: https://dev.payment.com/order/%s/status
    timeout: 15 # in minutes
